Kotlin. Homework #1. Task #2
Belgrak/SPBU_Kotlin_Homeworks pull request #2
Opened 2022-02-26 06:56 UTC by Belgrak

2022-02-27 18:22 UTC, GirZ0n requested changes

2022-02-27 18:22 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        print("Prime numbers: " + sieveOfEratosthenes(num).joinToString())
Хотелось бы видеть какое-то специальное сообщение, если мы получили от функции пустой список.

2022-02-27 18:22 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +}
Честно говоря, если бы не название функции, то я бы не понял, что это решето Эратосфена)) Может попроще напишем?)

2022-02-27 18:22 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +    val tempList = primeNumbers.toList()
Плохое название.

2022-02-27 18:22 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +fun sieveOfEratosthenes(n: Int): MutableList<Int> {
Кажется, что если передали в качестве `n` отрицательное число, то стоит кинуть исключение. Это можно сделать с помощью функции [`require`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html#require).

2022-02-27 18:22 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        val num = readLine()!!.toIntOrNull() ?: throw TypeCastException("Integer was expected")
Нужно всеми силами избегать `!!`. Тут явно можно обойтись без него)

2022-02-27 18:22 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/SieveOfEratosthenesTest.kt
> +        assertArrayEquals(intArrayOf(2, 3, 5), sieveOfEratosthenes(5).toIntArray())
Возьми число побольше, а то `5` слишком маленькое))

2022-03-03 20:36 UTC, GirZ0n requested changes
Супер! Стало лучше)

2022-03-03 20:36 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/SieveOfEratosthenesTest.kt
> +            sieveOfEratosthenes(1000).toIntArray()
А зачем `toIntArray`?) Ты же можешь использовать `listOf` вместо `intArrayOf`)

2022-03-03 20:36 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/SieveOfEratosthenesTest.kt
> +        assertThrows<IllegalArgumentException> { sieveOfEratosthenes(-1) }
Также будет не лишним проверять сообщение. Это можно делать с помощью [`assertFailsWith`](https://www.baeldung.com/kotlin/assertfailswith#1-asserting-exception-attributes).

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        val num = readLine()?.toIntOrNull() ?: throw TypeCastException("Integer was expected")
А зачем ты так хочешь сам кинуть исключение?) Ты можешь просто проверить num на null, и если это так, то просто выводи сообщение `Integer was expected` и завершай работу программы)

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        val num = readLine()?.toIntOrNull() ?: throw TypeCastException("Integer was expected")
`require` кидает `IllegalArgumentException`. Так что вместо своего `TypeCastException` лови лучше `IllegalArgumentException`.

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        print(if (result.isEmpty()) "There aren't any prime numbers(" else "Prime numbers: " + result.joinToString())
Да, записано в одну строчку, но не читаемо же)

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +                isPrimeNumber[j] = false
Несмотря на то, что ты можешь не ставить фигурные скобки в данном случае, но лучше их всё же ставить, чтобы код был согласованнее)

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        if (isPrimeNumber[i] && i * i <= n)
Кажется, что `for` и второе условие в `if` можно объединить.

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +    if (n == 0) return emptyList()
Давай лучше так напишем: 
```kotlin
if (n == 0) {
    return emptyList()
}
```

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +        if (isPrimeNumber[i] && i * i <= n)
А, ну у тебя там дальше `for (j in i * i..n step i)`, но если i * i будет больше n, то range будет пустым и цикл просто не выполнится. Так что, если я не ошибаюсь, условие `i * i <= n` вообще можно убрать)

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +            for (j in i * i..n step i)
Давай поставим тут скобки `i * i`.

2022-03-03 20:36 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +    return isPrimeNumber.flatMapIndexed { index, b -> if (b) listOf(index) else emptyList() }
Кажется, что тебе пригодится здесь [`mapIndexedNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-indexed-not-null.html#mapindexednotnull))

2022-03-05 08:59 UTC, GirZ0n requested changes
Балдёж. Теперь всё супер) Оставил несколько небольших замечаний. Как только ты их поправишь я апрувну ПР) 

P.S. Пожалуйста не пиши сплошную стену коду) Лучше группируй команды по смыслу, чтобы легче было читать)

2022-03-05 08:59 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +    val isPrimeNumber = BooleanArray(n + 1) { true }.toTypedArray()
Хмм, да, `mapIndexedNotNull` не хочет чего-то работать с `BooleanArray`. Тогда давай вместо `BooleanArray` будем использовать `MutableList`. Просто создавать `BooleanArray`, а затем сразу же конвертировать его в typed array как-то странно)

2022-03-05 08:59 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework1/task_2.kt
> +    return isPrimeNumber.mapIndexedNotNull { index, b -> if (b) index else null }
`b` -- плохое название)

2022-03-05 08:59 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework1/SieveOfEratosthenesTest.kt
> +        assertThrows<IllegalArgumentException> { sieveOfEratosthenes(-1) }
Ты немного не так понял) Параметр `message` необходим лишь для вывода в консоль сообщения в том случае, если функция всё же не кинет исключение. Я же скинул ссылку на то как нужно проверять сообщение) То есть тебе нужно написать что-то такое:
```kotlin
@Test
fun testWithNegativeNumber() {
    val exception = assertFailsWith<IllegalArgumentException> { sieveOfEratosthenes(-42) }
    assertEquals("Number must be non-negative, was -42", exception.message)
}
```

2022-03-05 09:16 UTC, GirZ0n commented
@Belgrak, я тут понял, что третье ревью должен делать не я, а Егор. Так что тебе немного повезло)) Я сейчас запрошу ещё одно ревью у Егора.

2022-03-08 10:43 UTC, SpirinEgor approved these changes

2022-03-08 10:43 UTC, merged