Kotlin. Homework #1. Task #3
Belgrak/SPBU_Kotlin_Homeworks pull request #3
Opened 2022-03-11 09:14 UTC by Belgrak

2022-03-13 10:53 UTC, illided requested changes

2022-03-13 10:53 UTC, illided commented on build.gradle.kts
> +    testImplementation(kotlin("test"))
Зачем?)

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +class AddFirst(private val listOfInts: MutableList<Int>, private val listOfArguments: List<Int>) : Action {
`listOfArguments`? А что если я туда запихаю listOf(1,1,1,1,1,1,1,1,1,1)? Мне кажется такое не должно быть возможно впринципе

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        listOfInts.removeAt(listOfInts.size)
Ну или `removeLast`

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        listOfInts.add(listOfInts.size, listOfArguments[0])
Насколько я помню если вставляешь в конец не обязательно указывать индекс

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        require(listOfArguments.size >= 2) { "Too few arguments" }
А если будет 69420 аргументов?

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        val aIndex = listOfArguments[0]
Что такое `aIndex` и `bIndex`?) Лучше называть переменные говорящими именами, а не как в учебнике по математике

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +            Collections.swap(listOfInts, aIndex + sign * (i - 1), aIndex + sign * i)
Слишком сложно)
В котлине можно намного проще поменять позицию элемента

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/PerformedCommandStorage.kt
> +        listOfActions.removeAt(listOfActions.lastIndex)
Можно эти две команды соединить в 
`listOfActions.removeLast().cancelAction()`

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +fun commandHandler(
Функции называем глаголами, обьекты существительными

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +    firstArgument: Int?,
А если захочу добавить комманду с тремя аргументами?)

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +                else -> {
Лучше заменить на when и добавить условие `it.size == 3`
А на else пусть кидается исключение

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +fun commandHandler(
Чот я посмотрел на эту функцию и на те что выше. Давай сделаем это все полноценным классом. А то сейчас просто размазано по файлу неприятно

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        listOfInts.removeAt(0)
`removeFirst()`

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +        inputLine = readLine() ?: return
А может лучше попросить еще раз ввести команду?

2022-03-13 10:53 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +        inputLine = readLine() ?: return
И добавь возможность выйти из твоего приложения)

2022-03-13 11:48 UTC, Belgrak commented on build.gradle.kts
> +    testImplementation(kotlin("test"))
У меня просто в предыдущем задании использовался assertFailsWith, да и в этом тоже

2022-03-13 11:49 UTC, illided commented on build.gradle.kts
> +    testImplementation(kotlin("test"))
Не, конкретно к самой зависимости претензий нет. Я не понимаю зачем ты у нее строчку поменял :)

2022-03-14 06:34 UTC, Belgrak commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +        inputLine = readLine() ?: return
Так там null же вроде только при прерывании ввода
![image](https://user-images.githubusercontent.com/63420603/158116794-89e019f5-45c1-47f5-a65f-a16734f98280.png)
А при всех неизвестных командах, в том числе пустой строки, выводится сообщение и пользователь вновь вводит

2022-03-24 20:37 UTC, illided requested changes
Уже сильно лучше. Следующий ревью кидай на Егора

2022-03-24 20:37 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        listOfInts.add(indexTo, listOfInts.removeAt(indexFrom))
Сложная логика, лучше разделить на две строчки

2022-03-24 20:37 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +        listOfInts.add(indexFrom, listOfInts.removeAt(indexTo))
Здесь то же самое

2022-03-24 20:37 UTC, illided commented on src/main/kotlin/homeworks/homework1/Action.kt
> +interface Action {
Можно сделать одно крутое изменение: положить list как аргумент doAction. Тогда станет сразу проще создавать `Action` и все функцию сразу упростятся

2022-03-24 20:37 UTC, illided commented on src/main/kotlin/homeworks/homework1/CommandHandler.kt
> +            "addFirst" -> addFirst(commandStorage, listOfInts, listOfArguments[0])
Давай сделаем Enum

2022-03-24 20:37 UTC, illided commented on src/main/kotlin/homeworks/homework1/CommandHandler.kt
> +            "exit" -> exitProcess(0)
Такое себе убивать приложение из класса)

2022-03-24 20:37 UTC, illided commented on src/main/kotlin/homeworks/homework1/task_3.kt
> +        inputLine = readLine() ?: return
Понял, зря быканул. Добавь тогда этот комментарий сюда

2022-03-24 20:37 UTC, illided approved these changes

2022-03-25 10:15 UTC, SpirinEgor requested changes
Наворатил лишних сущностей, как мне кажется, но да ладно.
Поправь тот кринж, в остальном ок

2022-03-25 10:15 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    }
![image](https://user-images.githubusercontent.com/22539802/160101195-8dd36016-64aa-4161-9ef9-39b017abf95e.png)

2022-03-25 10:36 UTC, Belgrak commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    }
хахахаха, это просто была проверка ревьюверов на бдительность)))

2022-03-25 11:00 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    fun isRunning() = status
Следующий шаг -- сделать приватный set и публичный get у `status`

2022-03-25 11:00 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    }
Ух, как бы потом ответная проверка не прилетела :)

2022-03-25 11:12 UTC, Belgrak commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    fun isRunning() = status
Так там же у status `private var`. Или я чего-то не понял?

2022-03-25 11:55 UTC, Belgrak commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    fun isRunning() = status
@SpirinEgor

2022-04-04 15:50 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/Program.kt
> +    fun isRunning() = status
Я к тому, что нет смысла тут отдельно на функции дробить, можно сделать вот так:
```kotlin
var status = IS_RUNNING
    private set
```

Сейчас ещё посмотрел на окружение -- что-то странное с IS_RUNNING и ERROR. Зачем надо было в отдельные переменные класть булы. То есть надо либо status переименовать в is_running и не плодить непонятные переменные. Либо сделать отдельный Enum с возможными значениями статуса программы.

2022-04-07 15:10 UTC, SpirinEgor approved these changes

2022-04-07 15:10 UTC, merged