Kotlin. Homework #3. Task #1
Belgrak/SPBU_Kotlin_Homeworks pull request #6
Opened 2022-04-15 20:45 UTC by Belgrak

2022-04-17 13:58 UTC, GirZ0n commented
:(
![image](https://user-images.githubusercontent.com/55441714/163716648-757ea861-e6bf-420e-a6ab-e364df021f7a.png)

Как исправишь, назначь меня снова, и получше тестируй код, который ты отправляешь :)

2022-04-17 14:05 UTC, Belgrak commented
> 

Странно, у меня на двух устройствах все нормально запустилось(...

2022-04-17 14:09 UTC, GirZ0n commented
Ты точно такой же код запускаешь у себя как и у меня на скрине?

2022-04-17 14:12 UTC, Belgrak commented
> Ты точно такой же код запускаешь у себя как и у меня на скрине?

Да(если речь про task1.3.kt). Причем на одном устройстве я только обновил проект, только появилась эта ветка, и там все работает

2022-04-17 14:29 UTC, GirZ0n commented
Проверил на 3 устройствах. Везде падает :( Ты все изменения запушил?)

2022-04-17 14:37 UTC, Belgrak commented
Сейчас удалось тоже самое словить, буду исправлять))) Извиняюсь за беспокойство

2022-04-17 14:41 UTC, GirZ0n commented
Отлично) Ещё одна вещь: по моей информации надо было реализовать MutableMap, а не обычный Map)

2022-04-23 11:49 UTC, GirZ0n requested changes
![image](https://user-images.githubusercontent.com/55441714/164893258-e0b34656-2d59-4c9b-810a-bddbfcbb4b0a.png)

2022-04-23 11:49 UTC, GirZ0n commented on src/test/kotlin/homeworks/homework3/AVLTreeTest.kt
> +internal class AVLTreeTest {
Тестов мало :( Используй параметризованные тесты, чтобы избежать повторения кода.

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    override var values: MutableCollection<V> = mutableListOf()
Вместо того, чтобы постоянно следить за этими переменными, можно переопределить их метод `get` так, чтобы при обращении производился обход дерева и тем самым собирались нужные значения. Да это не слишком эффективно, но кажется, что нам не очень важно как быстро мы будем получать значения этих полей)

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +            return null
Скобочки забыл

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
Можно же сразу в одну строку написать)

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
Тоже можно сразу одной строкой записать)

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    }
И тут можно в одну строку :)

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/Node.kt
> +    }
Опять же можно сразу без `return` через `=`.

2022-04-23 11:49 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/Node.kt
> +    fun toString(separatorCount: Int): String {
Можешь тут поставить дефолтное значение, чтобы в самом дереве не указывать `0` при вызове.

2022-04-24 12:15 UTC, Belgrak commented on src/main/kotlin/homeworks/homework3/Node.kt
> +    fun toString(separatorCount: Int): String {
В таком случае, используется toString для Any, а не Node. А сделать override нельзя, так как передается аргумент

2022-04-30 09:45 UTC, GirZ0n requested changes
:fire:. Оставил небольшие замечания. Как поправишь -- апрувну ПР)

2022-04-30 09:45 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/AVLTree.kt
> +    override fun containsKey(key: K) = key in keys
Лучше всё же уметь получать ключ за O(log(n)), у тебя есть метод `get`, который ты здесь можешь использовать)

2022-04-30 09:45 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/Node.kt
> +        }
А может тогда здесь использовать сразу `let`? 
```kotlin
rightChild?.let { nodeAsString += it.toString(separatorCount + 2) }
```
Кажется так будет покрасивше)

2022-04-30 09:45 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/Node.kt
> +        }
ну и с `leftChild` также)

2022-04-30 09:45 UTC, GirZ0n commented on src/main/kotlin/homeworks/homework3/Node.kt
> +    }
Лучше использовать `emptyList()`, а не `listOf()` :)

2022-04-30 13:58 UTC, GirZ0n approved these changes
Красотища

2022-05-02 18:41 UTC, SpirinEgor approved these changes
👍

2022-05-02 18:42 UTC, merged