Kotlin. Homework #4. Task #1
Belgrak/SPBU_Kotlin_Homeworks pull request #7
Opened 2022-04-16 20:42 UTC by Belgrak

2022-05-29 21:46 UTC, elena-lyulina requested changes
Выглядит неплохо, посмотри на тесты и мои комменты и будет класс :)

2022-05-29 21:46 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/mergeSort.kt
> +fun <E : Comparable<E>> MutableList<E>.mergeSort(count: Int = 1, asynchronousMode: Boolean = false): MutableList<E> {
если есть несколько режимов (в данном случае -- многопоточный, асинхронный), лучше сделать enum и там хранить разные режимы, и соответственно в функцию передавать нужный режим. Булеан позволяет поддерживать только два режима, когда как енам -- более гибок (можно добавлять новые режимы) + сложнее ошибиться в передаче нужного режима (тогда будет видно его имя, а не просто false/true)

2022-05-29 21:46 UTC, elena-lyulina commented on src/test/kotlin/homeworks/homework4/MergeSortKtTest.kt
> +        assertEquals(expected, list.mergeSort(10))
хочется тесты с разным количеством потоков

2022-05-29 21:46 UTC, elena-lyulina commented on src/test/kotlin/homeworks/homework4/MergeSortKtTest.kt
> +        assertEquals(expected, list.mergeSort(10))
а теперь попробуй запустить тесты с assertEquals(expected, list) :) так и должно быть?

2022-05-29 21:46 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/model.kt
> +    val path = ggsave(plot, THREADS_CHART_NAME, path = "src/main/resources")
папку с ресурсами лучше получать автоматически через getResource()

2022-05-29 21:46 UTC, elena-lyulina commented on src/main/kotlin/homeworks/homework4/view/MainView.kt
> +            Slider(
я не очень понимаю, зачем нужен вообще слайдер и сгенерированный список из 100 элементов, если он все равно не используется для графиков?..

2022-05-30 06:51 UTC, Belgrak commented on src/main/kotlin/homeworks/homework4/view/MainView.kt
> +            Slider(
просто демонстрация корректности сортировки)

2022-05-30 07:21 UTC, Belgrak commented on src/main/kotlin/homeworks/homework4/model.kt
> +    val path = ggsave(plot, THREADS_CHART_NAME, path = "src/main/resources")
он вроде возвращает файл, и если и использовать getResource, то нужно создать пустой файл в той директории,  либо я не туда смотрю...

2022-06-01 12:12 UTC, elena-lyulina approved these changes

2022-06-01 12:12 UTC, elena-lyulina commented
надо только конфликты пофиксить

2022-06-02 11:36 UTC, merged